runtime: php8  # version of php
env: flex     # set app engine env to standard
runtime_config:
  document_root: .
# for detecting static files in the public folder
handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
env_variables:
APP_NAME: Laravel
APP_STORAGE: /tmp
VIEW_COMPILED_PATH: /tmp
APP_ENV: production
APP_KEY: base64:zCx0eGjxmWwQnMxbcfcbehZpgvmEmhWuhxY0n9UU8mQ=
APP_DEBUG: true
APP_URL: http://localhost

LOG_CHANNEL: stack
LOG_DEPRECATIONS_CHANNEL: null
LOG_LEVEL: debug

DB_CONNECTION: mysql
DB_HOST: localhost
DB_PORT: 3306
DB_DATABASE: video_upolad
DB_USERNAME: video-laravel-project
DB_PASSWORD: "AMck-zxn^c~Kj&(#"

BROADCAST_DRIVER: log
CACHE_DRIVER: file
FILESYSTEM_DISK: local
QUEUE_CONNECTION: sync
SESSION_DRIVER: file
SESSION_LIFETIME: 120

MEMCACHED_HOST: 127.0.0.1

REDIS_HOST: 127.0.0.1
REDIS_PASSWORD: null
REDIS_PORT: 6379

MAIL_MAILER: smtp
MAIL_HOST: mboxhosting.com
MAIL_PORT: 25
MAIL_USERNAME: noreply@talibdbouk.com
MAIL_PASSWORD: "DaASc@6=8Esp{Pyj"
MAIL_ENCRYPTION: tls
MAIL_FROM_ADDRESS: "noreply@talibdbouk.com"
MAIL_FROM_NAME: "Video Project"

AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY: 
AWS_DEFAULT_REGION: us-east-1
AWS_BUCKET: 
AWS_USE_PATH_STYLE_ENDPOINT: false

PUSHER_APP_ID: 
PUSHER_APP_KEY: 
PUSHER_APP_SECRET: 
PUSHER_HOST: 
PUSHER_PORT: 443
PUSHER_SCHEME: https
PUSHER_APP_CLUSTER: mt1

VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
VITE_PUSHER_HOST: "${PUSHER_HOST}"
VITE_PUSHER_PORT: "${PUSHER_PORT}"
VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

PAYPAL_MODE: sandbox
PAYPAL_SANDBOX_CLIENT_ID: AR9D_eor3S9YLegpuXblAzKKo3NGLqCWHwPHNxxyXsL7koBsqnW2PfLvTFsz5tjh29-5PmCe1phoFGir
PAYPAL_SANDBOX_CLIENT_SECRET: EI8Xw1zYOW38ONpDGFTmYXOQnYXDV1gku0UJh6hngs70o_SmmBOfKcY-RF1pGGDMNRM8JC58L9AXUMAV
